import type { AreaSlug, ServiceSlug } from "@/lib/lakeside";

export const SERVICE_LONG: Record<ServiceSlug, string[]> = {
  "cosmetic-dentistry": [
    "Cosmetic dentistry in Kenner at Lakeside Dental Care is not a separate boutique down the street. Drs. Rubia Kapusta and Matthew Henson do the veneer, crown, and whitening work in Suite 210, on the same floor as the endodontist, periodontist, and orthodontist. A Kenner smile that needs a gum lift plus porcelain does not get farmed out to three parking lots.",
    "The official homepage puts porcelain veneers, dental crowns, and Zoom whitening on the cosmetic list. Zoom in-office uses a light-activated gel to shift shade in a single visit; the take-home gel is worn four to eight hours per application. Shade assessment happens in the chair, not from a drugstore strip.",
    "Porcelain veneers cover the front of a tooth that is chipped, spaced, or stained past bleaching. Crowns rebuild a tooth that has lost walls to decay or a large filling. Composite fillings stay in the general-dentistry column; the cosmetic column is the visible edge — the teeth you show on Veterans Blvd.",
    "Dr. Henson’s smile gallery on the old site shows Invisalign plus recontouring, lower-arch porcelain, and full-mouth cases that mix crowns, veneers, dentures, and implants. Those cases are his, photographed for the practice, not stock mouths. This rebuild does not invent patient faces.",
    "A cosmetic consult in Kenner starts with photographs and, when the bite or the bone is in question, a KaVo OP 3D scan. iTero Element 5D Plus captures the arch without goop. The orthodontist, Dr. Schwab, can stage aligners before porcelain so the veneers sit on teeth that already meet.",
    "Patients from Metairie, New Orleans, and LaPlace use this Kenner cosmetic dentist because the specialist stack is already here. Whitening a single dark tooth after a root canal can loop Dr. Dyer in without a referral letter that leaves the building.",
    "Insurance may cover a crown that is structurally necessary and decline a veneer that is elective. The desk lists Delta, Guardian, Humana, MetLife, Ameritas, Cigna, Renaissance, Aetna, Careington, plus CareCredit, Cherry, and Kleer. Ask which code applies before the porcelain is milled.",
    "Sedation is available if the camera, the tray, or the length of a veneer appointment is the barrier. Oral conscious sedation and nitrous are the two published methods. The cosmetic result still has to be designed while you can consent; sedation is for the appointment, not the plan.",
    "Existing porcelain and tetracycline banding do not bleach the way enamel does. A Kenner cosmetic dentist will say so in the consult instead of selling a Zoom tray that cannot reach the stain. Veneers or crowns become the honest path on those teeth.",
    "Crown lengthening with Dr. Wilkerson is how a short tooth becomes a veneer candidate. The smile gallery already credits her connective-tissue graft on a case Dr. Henson restored. That is the in-house sequence this office exists to run, not a brochure mash-up.",
    "Electric hand-pieces and the high-power microscope are listed on the technology page for the precise cuts a veneer margin needs. Digital X-rays stay at about one-sixth of film dose. The intraoral camera puts the chip on a monitor so the plan is not a lecture you cannot see.",
    "Whitening sensitivity is real. The desk will tell you if a desensitizing protocol is part of the Zoom visit. This page does not invent a product name the official site did not publish.",
    "A full-mouth cosmetic sequence in Kenner can occupy more than one Friday. Hours end at 4:00pm Monday through Thursday and 3:00pm Friday. Do not book a six-hour veneer try-in at 2:15 on a Friday and expect the lab to stay.",
    "Parking is the plaza lot at 2400 Veterans Blvd., not a New Orleans garage. Bring a shade reference from an old photograph if you have one. Leave with tooth numbers, material, and a doctor named on paper.",
    "This Kenner cosmetic dentist page does not sell six-month guarantees or stock before-and-afters. Official stills of the doctors and the building are used; operatory and porcelain plates are empty atmospheres, not fake patients.",
    "Book cosmetic dentistry in Kenner through NexHealth or call (504) 833-3200. Suite 210 is on the second floor of 2400 Veterans Blvd., the glass plaza with the fountain court. Bring a shade you like from an old photograph. Leave with a plan that names the tooth, the material, and the doctor.",
  ],
  "general-dentistry": [
    "A Kenner dentist who still does exams and cleanings in the same suite as specialty care is the point of Lakeside Dental Care. Drs. Rubia Kapusta, Matthew Henson, and Olivia Stassen hold the general chairs. The endodontist, periodontist, and orthodontist are down the hall, not across town.",
    "General dentistry here covers the unglamorous work that keeps a mouth: exams, cleanings, digital X-rays, intraoral photos, fillings, and the decision about whether a tooth needs a specialist. Composite fillings replace decay without a silver glint. Sealants and child visits are on the published service list.",
    "Dr. Kapusta trained at the Federal University of Espirito Santo and finished a two-year hospital residency at LSU. She holds an AGD fellowship — the site notes that about five percent of general dentists earn it. Dr. Henson is LSU 2018 plus UCLA AEGD. Dr. Stassen is LSU-trained and lists Invisalign among general skills.",
    "The first visit in Kenner is an exam, not a sales deck. Radiographs are taken when the guidelines say so; digital sensors cut exposure to about one-sixth of film. An intraoral camera puts the cracked cusp on a monitor so you are not nodding at a description you cannot see.",
    "Family range is published as all ages for Dr. Stassen. The office languages — English, Spanish, French, Chinese, Vietnamese, Haitian Creole, Portuguese — sit at the same desk that schedules a cleaning. Interpreters are on staff, not a phone tree.",
    "A filling that fails into a root canal stays in the building with Dr. Dyer. A gum pocket that needs osseous work stays with Dr. Wilkerson. A crowding complaint can move to Dr. Schwab without a new patient packet at a second brand.",
    "Hours are Monday through Thursday 8:30am–4:00pm and Friday 8:00am–3:00pm. That is the contact-page clock, not a third-party listing. Call (504) 833-3200 if you need a same-week hygiene opening; the web form is a callback.",
    "Kenner, Metairie, New Orleans, and LaPlace all feed this general chair. Jefferson Parish and Orleans Parish are named on the site. One address: 2400 Veterans Blvd. Suite 210.",
    "Recall is a date the hygienist writes down, not a postcard you ignore. The Kenner dentist who saw the cracked molar last winter is the one who should see the crown margin this spring. Ask the desk to keep you on the same doctor if that continuity matters.",
    "Electric hand-pieces are listed for the precise parts of restorative work. The KaVo OP 3D is in the suite if the exam finds an implant or a hidden canal. You do not leave Kenner for a scan the office already owns.",
    "Insurance on the published list: Delta Dental, Guardian, Humana, MetLife, Ameritas, Cigna Dental, Renaissance Dental, Aetna, Careington, Dental Plans. Cash, checks, Visa, Mastercard, American Express, Discover, CareCredit, Cherry, and Kleer membership cover the rest. Confirm in-network before the filling is billed as out-of-network.",
    "This Kenner dentist office does not publish weekend hours on the contact page. Demandforce listings that mention Saturday by appointment are ignored here. The clock used on this rebuild is the official contact-us schedule only.",
    "Children who need sealants and adults who need four-surface composites sit in the same general column. Dr. Stassen’s bio is the all-ages sentence. Pediatric hospitals and oral-surgery ORs are not claimed.",
    "Pain that wakes you at 2am still starts with a phone call to (504) 833-3200 when the desk is open. This page does not invent an emergency number the official site did not print. If the tooth needs Dr. Dyer, the general exam is how that handoff is written.",
    "Staff from more than seven countries work the Kenner floor. That is the about-page sentence. A cleaning can be explained in Spanish or Vietnamese without a speakerphone interpreter in another state.",
    "Keep the Kenner dentist visit on a recall the hygienist actually writes down. Bring the insurance card from the listed carriers or ask about Kleer if you have none. General dentistry is the floor the specialists stand on.",
  ],
  endodontics: [
    "Root canal therapy in Kenner does not require a drive into a medical-office park you have never seen. Dr. Regine Dyer is the endodontist at Lakeside Dental Care. She shares Suite 210 with the general dentists who diagnosed the tooth.",
    "Dr. Dyer was born in New Orleans, finished Xavier University of Louisiana, earned her DDS at Meharry in 2010, completed a GPR at Truman Medical Center Hospital – Lakewood in 2011, and her Certificate of Endodontics at LSU in 2014. She is an appointed part-time associate clinical professor in the LSU Department of Endodontics.",
    "The advanced-technology page lists high-power microscopes for precision restorations. Endodontic work lives on that microscope. Digital imaging and the KaVo OP 3D add a three-dimensional look at canals that a periapical film can hide.",
    "The practice’s Facebook page states that Dr. Dyer offers the GentleWave Procedure, using fluid dynamics and sound to disinfect anatomy that files miss. That claim is theirs, on their official social account, not a brochure we invented.",
    "A Kenner endodontist in the same building means the tooth that hurts on a Thursday can be opened, cleaned, and returned to Dr. Henson or Dr. Kapusta for the crown without a second intake. Apicoectomy and retreatment are on the published endodontic list.",
    "Dental anxiety is named on the old homepage as a reason people delay. Oral sedation and nitrous are available for the visit. You still sign the plan awake.",
    "Insurance coding for root canals varies by tooth number and by whether the canal is initial or retreatment. The desk will map Delta, Guardian, MetLife, and the rest of the listed carriers. CareCredit and Cherry exist if the molar is not in the annual maximum.",
    "Patients from Metairie and New Orleans use this Kenner endodontist because the general team already has the chart. LaPlace patients get the same microscope without a CBD parking garage.",
    "A tooth that needs a root canal is usually a tooth the general dentist wants to keep. Extraction is the other door. Dr. Dyer’s chair is how Lakeside tries to keep the tooth, then hands it back for a crown in the same Kenner suite.",
    "Retreatment is on the published list because a canal done years ago in another parish can still fail. Bring the old films on a disc. The KaVo OP 3D is how hidden anatomy is argued with, not a second opinion across town.",
    "Dr. Dyer teaches part-time at LSU. That is an official appointment, not a slogan. The Kenner endodontist who opens your molar on a Tuesday may be the same person a resident hears on a Thursday.",
    "GentleWave is named on Facebook, not on every inner page of the old site. Ask in the consult if your tooth is a candidate. This rebuild does not turn a social post into a promise for every canal.",
    "Hours still close at 4:00pm most weekdays and 3:00pm Friday. A swollen face at 3:40pm on Friday meets a locked door. Call (504) 833-3200 while the desk is staffed.",
    "Sedation for a Kenner root canal is the same oral-conscious and nitrous stack as the rest of the suite. Local anesthetic still numbs the tooth. Sedation is the layer for people who would cancel.",
    "After the canal, the general dentist in Suite 210 seats the crown. That is the point of sharing a floor. Do not leave Kenner with a temporary and a referral to a stranger for the final porcelain unless the case requires it.",
    "Book Dr. Dyer through NexHealth or call (504) 833-3200. Bring any outside X-rays on a disc if another office started the tooth. The canal work stays in Kenner.",
  ],
  periodontics: [
    "Periodontics in Kenner at Lakeside Dental Care is Dr. Corinthia Wilkerson’s chair. She is the periodontist named on the homepage six. The official group photograph does not include her portrait; her bio is on the periodontist page and is the source used here.",
    "Dr. Wilkerson studied Biology at Spelman, earned a Master’s in Biomedical Sciences with a concentration in oral biology at Rutgers, her DDS plus public-health certificates at Meharry, and a Master of Medical Sciences and Certificate in Periodontology from the Harvard School of Dental Medicine. She is a three-time HSDM Division of Periodontology Fellow.",
    "Her published clinical range: periodontal regeneration, guided bone and tissue regeneration, prosthodontically driven implant placement, and peri-implant disease. The American Academy of Implant Dentistry, the Academy of Osseointegration, and the AAOMS have recognized her implant work, per the official bio.",
    "Osseous surgery, crown lengthening, and connective-tissue grafts are on the practice’s periodontal menu. The smile gallery credits Dr. Wilkerson for esthetic crown-lengthening and a connective-tissue graft on a cosmetic case restored by Dr. Henson. That is the in-office loop this Kenner periodontist exists to provide.",
    "Maintenance after active therapy is its own page on the old site. The general dentist and the periodontist split the recall. You do not graduate out of cleanings because the pockets closed once.",
    "KaVo OP 3D imaging plans bone grafts and implant sites without sending you to an imaging center across Jefferson Parish. The restoration still comes back to the general dentists in the same suite.",
    "Gum disease is the leading cause of adult tooth loss; that sentence is on their maintenance page. The Kenner periodontist is how this office tries not to donate those teeth to a partial.",
    "Languages at the desk cover the parish. Hours are the published weekday clock. Book through NexHealth or (504) 833-3200 and ask for periodontal evaluation, not a generic cleaning, if you already know the pockets are the problem.",
    "This page uses a monogram for Dr. Wilkerson because no official individual portrait is on the staff photograph. A generated face would be a fake doctor. Initials are the honest substitute.",
    "Prosthetically driven implant placement is the sentence that keeps surgery and the crown in conversation. Dr. Henson or Dr. Kapusta names the tooth the restoration needs; Dr. Wilkerson places the fixture where that restoration can survive.",
    "Crown lengthening is not a cosmetic extra when a fracture sits under the gum. The Kenner periodontist exposes the margin so the general dentist can capture a clean impression. That visit can be stacked in Suite 210.",
    "Peri-implant disease is in the published skill list because implants are not maintenance-free. A Kenner implant that bleeds at the hygiene visit belongs back in the periodontal chair, not on a wait-and-see postcard.",
    "Metairie and New Orleans patients who were handed a perio referral at a strip-mall cleaning can keep the rest of the mouth here. LaPlace patients get the same Harvard-trained periodontist without a downtown medical-office maze.",
    "Insurance often files osseous surgery as major. Confirm the listed carriers. CareCredit, Cherry, and Kleer are the published alternatives if the annual maximum is already gone.",
    "Do not skip the medical history. Diabetes, smoking, and blood-pressure medicines change healing. The official bio does not list a miracle graft. Biology still decides.",
    "Metairie, New Orleans, and LaPlace patients who were told they need a periodontist can keep the rest of the mouth at Lakeside. One Kenner address holds both.",
  ],
  orthodontics: [
    "Orthodontics in Kenner is Dr. Catherine Schwab’s department at Lakeside Dental Care. She is ABO-certified as of 2002. Aligners, braces, and the occlusal plan live with her; the general dentists keep the rest of the mouth.",
    "Dr. Schwab received her dental and orthodontic education at LSU School of Dentistry, then a two-year functional occlusion course at the Roth-Williams Center in Burlingame. She taught in LSU’s orthodontic department from 2003 until 2015.",
    "Clear aligners and a wide range of braces are on the homepage orthodontic blurb. iTero Element 5D Plus is the digital impression system named on the technology page — no tray of putty for the scan that starts Invisalign-style treatment. Dr. Stassen also lists Invisalign among general skills, so some aligner visits stay with family dentistry when the case is limited.",
    "Corrective jaw surgery is mentioned on the old orthodontic summary. That is a hospital-level sentence, not a promise that Suite 210 is an OR. Ask Dr. Schwab which cases she keeps and which she coordinates.",
    "A Kenner orthodontist in the same suite as a periodontist matters when braces will move teeth through thin gum. Dr. Wilkerson can graft before the wire goes on. A Kenner endodontist matters when a traumatized incisor is in the aligner sequence.",
    "Adults from Metairie who delayed braces because they did not want a teen clinic waiting room use this office. Children still come; Dr. Stassen’s bio says all ages, and Dr. Schwab’s chair is not age-gated on the site.",
    "Insurance orthodontic riders are a different animal from cleaning benefits. The listed carriers may or may not have one. CareCredit and Cherry exist for the months of trays. Ask the desk for a written breakdown before the first aligner is printed.",
    "The smile gallery’s Invisalign plus recontouring case closed spaces in under six months, per their caption. Results are case-specific. This page does not invent a timeline for your arch.",
    "ABO certification in 2002 is a board exam, not a membership plaque. Dr. Schwab’s Kenner orthodontist listing carries that date because the official bio does. This rebuild does not add extra boards.",
    "Roth-Williams training is about how teeth meet, not only how they look in a selfie. A Kenner bite that destroys veneers will be a bite conversation before it is a porcelain conversation with Dr. Henson.",
    "iTero scans live in Suite 210. You are not sent to a mall kiosk for the impression that starts aligners. The Kenner orthodontist who plans the movement is the one who sees the scan.",
    "Limited Invisalign with Dr. Stassen and comprehensive mechanics with Dr. Schwab are not the same visit. The desk should tell you which chair you are actually booking. Ask.",
    "Retainers are how the Kenner result stays. This page does not invent a brand of retainer the official site did not name. Ask Dr. Schwab what she issues at debond.",
    "Hours are weekday. School-age patients from Kenner and Metairie need afternoon slots; those fill. Call (504) 833-3200 instead of hoping the NexHealth grid still has 3:30pm.",
    "New Orleans and LaPlace families use this Kenner orthodontist to keep hygiene and braces in one chart. A teenager’s cleaning and an aligner check can share a morning if the desk stacks them.",
    "Book an orthodontic consult in Kenner at 2400 Veterans Blvd. Suite 210. NexHealth or (504) 833-3200. Bring any prior panorex. Leave with a plan that names aligners, braces, or a referral — in writing.",
  ],
  "dental-implants": [
    "Dental implants in Kenner at Lakeside Dental Care are a team product: Dr. Wilkerson’s periodontal surgery, KaVo OP 3D planning, and restorations from the general dentists. The old homepage lists implants next to dentures and bridges as the replacement set.",
    "An implant is a root analog in bone, not a denture glue. CBCT from the KaVo OP 3D shows sinus floors, nerve canals, and the thickness you actually have. That scan happens in Suite 210. You are not sent to a mobile truck in a parking lot.",
    "Dr. Wilkerson’s Harvard perio certificate and implant recognitions are why the surgical side stays in-house. Dr. Henson’s gallery includes a case planned for four upper implants under a denture. That is his published work, not a stock before-and-after.",
    "Bridges still exist for patients who do not want surgery. Dentures still exist for arches that will not hold fixtures. The Kenner implant consult is supposed to name which of the three you are actually a candidate for.",
    "Healing time is biology, not marketing. Bone grafts and sinus work, when needed, add months. The general dentist does not seat the crown the afternoon the fixture goes in unless the case was designed that way.",
    "Peri-implant disease is in Dr. Wilkerson’s published skill list. Implants are not maintenance-free. Hygiene recall after the crown is seated is part of the implant, not an upsell.",
    "Insurance often treats implants as major or as excluded. The listed carriers, CareCredit, Cherry, and Kleer are the published payment stack. Get the code and the estimate before the surgical date.",
    "Metairie and New Orleans patients use this Kenner implant chair to keep the restorative dentist who already knows the bite. LaPlace patients get CBCT without a New Orleans imaging bill.",
    "Guided bone and tissue regeneration, named in Dr. Wilkerson’s bio, is how a thin ridge becomes a site. The Kenner implant plan starts with that scan, not with a catalog tooth on a poster.",
    "A failing root-canaled molar can become an implant, or it can become a bridge. Dr. Dyer and Dr. Wilkerson can argue that in the same hallway. This page does not pick the winner before the exam.",
    "Prosthodontically driven placement means the crown’s path is drawn before the drill. Drs. Kapusta, Henson, and Stassen restore. Dr. Wilkerson places. The Kenner floor is built for that conversation.",
    "Medications, bisphosphonates, and smoking change implant odds. Bring the list. This rebuild does not publish success percentages the official site did not print.",
    "Same-day teeth are a protocol, not a slogan. If Suite 210 offers an immediate provisional, the desk will say so for your case. Do not read a national ad into this Kenner page.",
    "Parking at the plaza matters on a surgical morning. Bring a driver if sedation is part of the visit. Friday 3:00pm close is a hard stop for recovery instructions.",
    "Jefferson Parish and Orleans Parish patients are named as served markets. The implant chair is still 2400 Veterans Blvd. Suite 210. There is no second surgical suite in Metairie.",
    "Call (504) 833-3200 or book NexHealth for a 3D scan visit. 2400 Veterans Blvd. Suite 210. Bring a list of medications. Implant dentistry starts with bone, not with a catalog tooth.",
  ],
  "sedation-dentistry": [
    "Sedation dentistry in Kenner at Lakeside Dental Care is oral conscious sedation and nitrous oxide. The oral-sedation page states a doctor is board certified to administer oral conscious sedation, the method they also call sleep dentistry.",
    "The old homepage says dental anxiety affects up to 40 percent of adults and up to 10 percent have severe dental phobia. That is their published reason for keeping sedation in the suite. It is not a diagnosis of you.",
    "Oral sedation is a pill from the benzodiazepine family — the page names Valium, Halcion, Xanax, or Ativan as the class, not a promise of a specific script. You need a driver. Nitrous is shorter-acting and does not require the same escort in every case; ask the desk which protocol they use.",
    "Advantages they list: treatment while you are calmer, less trouble sitting through a long visit, multiple procedures in one appointment, less discomfort after. Those are their bullets. Your medical history still decides if you are a candidate.",
    "Sedation does not replace local anesthetic. A root canal with Dr. Dyer or a graft with Dr. Wilkerson still gets numb. Sedation is the layer above the needle for people who would otherwise cancel.",
    "A Kenner sedation dentist who also has specialists in the building can finish more of the plan in the same sedated visit. That is the practical reason this office talks about full-mouth work under oral sedation.",
    "Tell the desk about sleep apnea, pregnancy, opioids, and alcohol before anyone hands you a pill. Board certification to administer is not a blank check. The medical history form is the real gate.",
    "Hours stay weekday. You will not be recovered for a Friday 3:00pm close if you arrive at 2:30. Book the sedation visit with time on both sides.",
    "Sleep dentistry is their phrase for oral conscious sedation, not a hospital general-anesthesia suite. You are not intubated in Suite 210. If you need that level of anesthesia, this Kenner office is supposed to say so and send you to the setting that can do it.",
    "Nitrous oxide is the shorter door. It can take the edge off a cleaning or a filling without a designated driver in every protocol. Ask. Do not assume the oral-sedation rules apply to gas, or the reverse.",
    "A long cosmetic or implant sequence is the visit type the old page describes as easier under sedation. Stacking Dr. Wilkerson and Dr. Henson in one calmer morning is the in-house version of that sentence.",
    "Insurance may cover the dentistry and decline the sedation fee. Confirm. CareCredit, Cherry, and Kleer are the published payment stack if the plan stops at the filling.",
    "New Orleans patients who plan a streetcar ride home after oral sedation are planning the wrong trip. Kenner is a car office. The driver who brings you is the driver who waits or returns.",
    "LaPlace and Metairie patients should not ride I-10 as the sedated passenger with a teenager at the wheel unless the desk clears the escort. Call (504) 833-3200 and ask the protocol out loud.",
    "This page does not invent a pediatric sedation program. Dr. Stassen sees all ages; the oral-sedation page is written in adult language. Ask the desk before you assume a child is a candidate.",
    "Call (504) 833-3200. Ask for a sedation consult, not only a cleaning. Suite 210, 2400 Veterans Blvd., Kenner. Bring the driver. Leave with a written list of what you may not do after the appointment.",
  ],
};

export const AREA_LONG: Record<AreaSlug, string[]> = {
  kenner: [
    "The Kenner dentist at Lakeside Dental Care sits at 2400 Veterans Blvd. Suite 210, a second-floor suite in the glass plaza with the fountain court. That is the only office. There is no second chair in Metairie and no pop-up in the Quarter.",
    "Kenner puts you between the airport and the lake. Patients who live off Williams Blvd, along Veterans, or near the Esplanade corridor reach Suite 210 without crossing the parish line. Parking is the plaza lot, not a garage downtown.",
    "Six specialists in one Kenner office is the pitch the homepage makes: general dentists, an endodontist, a periodontist, an orthodontist. A Kenner family can keep a cleaning, a root canal, and an aligner check on the same floor.",
    "Hours published on the contact page: Monday through Thursday 8:30am–4:00pm, Friday 8:00am–3:00pm. Phone (504) 833-3200. Fax (504) 833-0813. Online booking is NexHealth.",
    "Languages at this Kenner desk: English, Spanish, French, Chinese, Vietnamese, Haitian Creole, Portuguese. Staff come from more than seven countries. That is the official diversity sentence, not a slogan we added.",
    "Insurance listed for Kenner visits includes Delta, Guardian, Humana, MetLife, Ameritas, Cigna, Renaissance, Aetna, and Careington. Cash, checks, cards, CareCredit, Cherry, and Kleer cover the rest of the ways to pay.",
    "Technology on the Kenner floor: high-power microscopes, KaVo OP 3D, iTero 5D Plus, digital X-rays, intraoral camera. You do not leave Kenner for a scan the office already owns.",
    "Jefferson Parish is named as a served market. Kenner is the chair. If you are deciding between a strip-mall cleaner and a specialist stack, this is the specialist stack, still inside Kenner city limits.",
    "Louis Armstrong New Orleans International Airport is the western landmark. A Kenner dentist who can finish a crown the same week you land is still on the contact-page clock, not on a 24-hour promise. Call before you Uber from the terminal.",
    "Laketown Harbor, the Pontchartrain Center, and Kenner City Park sit north of Veterans. Suite 210 is the Veterans address, second floor, fountain court. Use the plaza lot. Do not circle the airport hotels looking for a dental sign.",
    "Williams Boulevard is the north-south spine. From the river side or the lake side, Veterans is the turn. The glass building is the official exterior used on this site — the dusk plate is atmosphere, the inset is the real facade.",
    "Esplanade Mall’s corridor still feeds this Kenner dentist. So do the neighborhoods off Vintage Drive and along Power Boulevard. The desk does not need a second Kenner zip code. 70062 is the one on the door.",
    "A Kenner child who needs sealants and a Kenner adult who needs Dr. Dyer can share a drop-off if the desk stacks the morning. That is the local use of a six-doctor floor. Ask for it by name.",
    "Friday close at 3:00pm is the Kenner trap. Airport traffic plus a 2:20pm hygiene visit is how people meet a locked door. Monday through Thursday to 4:00pm is the wider window.",
    "No public email is printed on the official site. This Kenner page does not invent one. Phone, fax, NexHealth, and the callback form are the four published doors.",
    "The official Facebook page is facebook.com/lakesidedentalcarekenner. Reviews are not copied here and are not placed in schema. A Kenner dentist with six specialists is still one address.",
    "Book the Kenner dentist at lakesidedentalcare.com’s NexHealth link or by phone. 2400 Veterans Blvd. Suite 210, Kenner, LA 70062. Ask for the doctor by name so the desk does not guess.",
  ],
  metairie: [
    "A Metairie dentist search often ends on Veterans Blvd. Lakeside Dental Care is the next stretch of that road, in Kenner, not a second brand. Metairie patients drive a few minutes to Suite 210 for a specialist set most Metairie strip offices do not staff.",
    "Dr. Stassen lives in Metairie, per her official bio. The office itself is Kenner. That is geography, not a Metairie clinic. You are still checking in at 2400 Veterans Blvd. Suite 210.",
    "Metairie patients who need a periodontist or an endodontist usually collect referrals. Here the referral is a hallway. Dr. Dyer and Dr. Wilkerson are in the same suite as the general exam that found the problem.",
    "Clearview, Fat City, Old Metairie, and the 17th Street Canal side all feed Veterans heading west. The plaza fountain is the landmark. Suite 210 is upstairs.",
    "Hours stay the Kenner clock: Mon–Thu 8:30–4, Friday 8–3. Call (504) 833-3200 from Metairie before you sit in the lot. The form on this site does not hold a chair.",
    "Spanish, Vietnamese, and the rest of the seven languages matter on the Metairie-Kenner corridor. Ask for an interpreter when you book, not at the window.",
    "Insurance cards from Metairie employers often match the listed carriers. If they do not, Kleer, CareCredit, and Cherry are the published alternatives. Do not assume a Metairie PPO is in-network until the desk says so.",
    "Aligners with Dr. Schwab, a gum graft with Dr. Wilkerson, and a crown with Dr. Henson can be sequenced for a Metairie patient without three new-patient forms. That is the reason to leave a closer cleaner.",
    "Lakeside Shopping Center is in Metairie. Lakeside Dental Care is not. The names collide in a search bar. The chair is the Kenner plaza on Veterans, not the mall parking deck. Say Suite 210 out loud to the rideshare driver.",
    "Causeway and Clearview both dump onto Veterans. From Old Metairie, Bonnabel to Veterans west is the boring, correct route. Fat City nightlife is irrelevant to a 8:30am exam; the Kenner door still opens then.",
    "The 17th Street Canal is the parish rumor line. Crossing it does not change the dentist. You are still a Metairie household using a Kenner specialist stack. Bring the Metairie insurance card and let the desk file from 70062.",
    "School calendars in Jefferson Parish fill afternoon hygiene. Metairie parents who want Dr. Stassen and Dr. Schwab on the same day should call, not tap the leftover NexHealth slot at 7pm. There is no 7pm. Friday dies at 3.",
    "A Metairie veneer consult can include Kenner perio and Kenner ortho in the same morning if the desk is told the whole complaint. Do not book “cleaning only” if the complaint is a dark front tooth and crowding.",
    "Sedation for Metairie patients still needs a driver who can return to Kenner, not a friend who will be in a Clearview office park. Oral sedation is a pill protocol. Nitrous is the shorter door. Ask which one you were actually scheduled for.",
    "This Metairie page does not invent a satellite, a shuttle, or a second phone. (504) 833-3200 is the Kenner desk. Fax (504) 833-0813. Facebook is the Kenner page.",
    "Drive from Metairie to the Kenner dentist. Park at the plaza. Take the elevator to 210. Book NexHealth if you already know the doctor. Call if you do not.",
  ],
  "new-orleans": [
    "New Orleans patients who want a specialist stack without a CBD parking hunt come to the Kenner office of Lakeside Dental Care. The mission on the about page names the reconstruction and renewal of New Orleans. The chairs are still in Suite 210.",
    "Dr. Dyer was born in New Orleans and lives there. Dr. Henson writes about the city’s food and culture in his bio. The practice is metropolitan in staff and Kenner in address. Both facts are official.",
    "Orleans Parish is listed among areas served. That does not mean a French Quarter operatory. It means a New Orleans patient can keep endo, perio, ortho, and general care on one Kenner floor.",
    "I-10 west, Veterans, or the airport road all reach 2400 Veterans Blvd. Allow lake traffic. Hours end at 4:00pm most weekdays and 3:00pm Friday; a 3:40 arrival from Bywater will meet a locked door.",
    "Sedation for New Orleans patients who have delayed dentistry is on the menu. Bring a driver who can return to Kenner. Do not plan a streetcar ride home from oral sedation.",
    "Languages cover a city that speaks more than English. Haitian Creole, Spanish, Vietnamese, French, Chinese, and Portuguese are published. Ask when you book.",
    "Uptown cleanings are everywhere. A Harvard-trained periodontist, an LSU endodontist who teaches, and an ABO orthodontist in the same suite are not. That is the New Orleans reason to cross into Jefferson.",
    "Insurance billed from a Kenner office still files to the listed carriers. Confirm the plan’s parish rules. CareCredit and Cherry remain available.",
    "The French Quarter does not hold a Lakeside chair. Neither does Uptown, Mid-City, or Algiers. New Orleans is named as a served city because the Kenner dentist keeps metropolitan patients, not because a second office opened on Canal Street.",
    "Parking downtown is the hidden fee of a CBD specialist tour. The Kenner plaza lot is the published alternative. Take I-10 west, exit toward Veterans, and look for the glass building with the fountain court — the official exterior on this site.",
    "A New Orleans root canal that used to mean a separate Uptown endodontist can stay with Dr. Dyer, then return to Dr. Kapusta or Dr. Henson for the crown without a second new-patient clipboard. That is the parish-crossing math.",
    "Haitian Creole at the Kenner desk is a published language, not a hope. New Orleans households that need it should ask when they book so the interpreter is actually in the suite that morning.",
    "Jazz Fest weeks and Mardi Gras parades do not add dental hours. The contact-page clock still ends at 4:00 and 3:00. If you are coming from the Bywater, leave earlier than your phone’s map claims.",
    "Dr. Henson’s bio is the New Orleans culture sentence. Dr. Dyer’s is the birthplace sentence. Neither fact moves the operatory. Suite 210 remains 2400 Veterans Blvd., Kenner, LA 70062.",
    "This New Orleans page does not copy star ratings from maps. Schema on this rebuild has no Review and no aggregateRating. Call (504) 833-3200 or use NexHealth.",
    "New Orleans to Kenner is one appointment, not a tour of specialists. 2400 Veterans Blvd. Suite 210. (504) 833-3200. NexHealth for the chair.",
  ],
  laplace: [
    "LaPlace patients listed on the official site as a served market reach Lakeside Dental Care by I-10 into Kenner. There is no LaPlace satellite. Suite 210 is the chair.",
    "St. John Parish dentistry often splits a root canal and a crown across two towns. This Kenner office keeps Dr. Dyer and the restoring general dentist on one floor so the LaPlace drive happens once per visit type, not once per specialty.",
    "Dr. Wilkerson’s periodontal surgery and Dr. Schwab’s aligners are the same trip. If a LaPlace teenager needs braces and a parent needs a crown, the desk can stack the morning.",
    "Leave time. Friday close is 3:00pm. A 2:15 departure from LaPlace in rain will miss it. Monday–Thursday to 4:00pm is the wider window. Call (504) 833-3200 before you get on the interstate.",
    "Seven languages at the Kenner desk include Spanish, which matters for St. John Parish households. Interpreters are in the office, per the about page.",
    "KaVo OP 3D means a LaPlace implant consult does not add a Metairie imaging stop. The scan, the plan, and the restoration stay in Kenner.",
    "Insurance from a river-parish employer may still be Delta, MetLife, or Cigna. Confirm. Kleer exists if it is not. Do not skip the benefit check because the drive felt long.",
    "Sedation is available if the combination of highway and dentistry is the barrier. Bring a second driver. Oral sedation is not a commute medication.",
    "Airline Highway is the older road; I-10 is the faster one on a dry morning. LaPlace to the Kenner dentist is still a parish change. Budget the bridge and the Veterans traffic, not only the map’s optimistic minutes.",
    "St. John Parish does not get a pop-up clinic on a Saturday. The official contact page does not publish Saturday hours. This rebuild ignores third-party listings that disagree.",
    "A LaPlace molar that needs a canal, a core, and a crown can be a two-visit Kenner story instead of three towns. Tell the desk the whole complaint when you book so Dr. Dyer and the general dentist are not scheduled six weeks apart by accident.",
    "River-parish employers sometimes carve dental out of medical. Bring the card. The Kenner desk files from 70062. If the plan hates Jefferson providers, you need to know that before the implant surgical date.",
    "Spanish at check-in is a published option. Ask for it in the NexHealth notes or on the phone. Do not assume the 8:30am assistant speaks it if you never said so.",
    "Kids in LaPlace schools still sit in Dr. Stassen’s all-ages chair and Dr. Schwab’s ortho chair. Stack a cleaning and an aligner check to save a second I-10 run. That is the only shuttle this office runs: a smarter schedule.",
    "No email is published. Fax is (504) 833-0813 if a St. John physician needs to send a medical-clearance note for sedation. Phone is faster.",
    "LaPlace to the Kenner dentist: 2400 Veterans Blvd. Suite 210. Book NexHealth for a named doctor. Ask the desk to same-day the specialist if the exam finds one.",
  ],
};

export const ABOUT_PARAS = [
  "The Kenner dentists at Lakeside Dental Care work from one suite at 2400 Veterans Blvd. Suite 210. Six specialists — general, endodontics, periodontics, and orthodontics — share that Kenner floor so a family does not collect referrals across Jefferson Parish. That is who, what, where, and why.",
  "Lakeside Dental Care’s mission, published on the about page, is to promote oral health by becoming the area’s leading provider of comprehensive dentistry while providing the absolute best care and service to patients. The practice also writes that it is committed to the reconstruction and renewal of New Orleans by providing quality dental care for the metropolitan area.",
  "For over 30 years the Kenner office has kept general dentists, a periodontist, an endodontist, and an orthodontist on one floor. The address has not split. 2400 Veterans Blvd. Suite 210 is still the lake office.",
  "Homepage doctors: Rubia Kapusta, DDS, MS; Regine Dyer, DDS; Catherine Schwab, DDS; Matthew Henson, DDS; Olivia Stassen, DDS; Corinthia Wilkerson, DDS. The staff photograph also includes Dr. Mahrufa Islam, who is not one of the six homepage names.",
  "Interpreters in the office speak Spanish, French, Chinese, Vietnamese, Haitian Creole, and Portuguese. Staff represent more than seven countries. That sentence is theirs.",
  "This about page does not invent owners, founding years beyond “over 30 years,” or reviews. Ratings exist on third-party sites; they are not copied into schema here.",
  "Dr. Kapusta earned her dental degree and Master of Science at the Federal University of Espirito Santo in 1999, finished a two-year hospital residency at LSU in 2002, and received an AGD fellowship in 2012. The official bio notes that about five percent of general dentists earn that fellowship. She lives in Slidell with Dr. Daniel Kapusta and their children Julia and Nicolas.",
  "Dr. Dyer was born in New Orleans, studied at Xavier, earned her DDS at Meharry in 2010, completed a GPR at Truman Medical Center Hospital – Lakewood in 2011, and her endodontic certificate at LSU in 2014. She is an appointed part-time associate clinical professor in LSU’s Department of Endodontics. The practice Facebook page notes GentleWave in her chair.",
  "Dr. Schwab took her dental and orthodontic education at LSU, then Roth-Williams functional occlusion in Burlingame. ABO certification arrived in 2002. She taught in LSU’s orthodontic department from 2003 to 2015. Painting, gardening, two dogs, and three children — Adam, Mark, and Susan — are the personal lines the official bio publishes.",
  "Dr. Henson graduated LSU School of Dentistry in 2018 and continued at UCLA’s AEGD. He writes that he takes nearly 100 hours of continuing education a year. New Orleans food, arts, and culture are the rest of his published paragraph.",
  "Dr. Stassen is the family dentist trained in general dentistry including Invisalign. She was born in Fayetteville, Arkansas, moved to New Orleans in 2017 for LSU dentistry, and lives in Metairie with her husband. All ages is her published range.",
  "Dr. Wilkerson’s path is Spelman biology, Rutgers oral biology, Meharry DDS with public-health certificates, then Harvard periodontology with a Master of Medical Sciences. She is a three-time HSDM Division of Periodontology Fellow. Regeneration, prosthodontically driven implants, and peri-implant disease are the clinical lines. No official individual portrait is on the group still, so this site uses her initials rather than a generated face.",
  "The official group photograph, used on this about page, names the front row as Dr. Catherine Schwab, Dr. Mahrufa Islam, and Dr. Rubia Kapusta, and the back row as Dr. Regine Dyer, Dr. Matthew Henson, and Dr. Olivia Stassen. Blue polos in that frame are staff. A second still names Anne, Dr. Dyer, Rosie, and Carol.",
  "Technology the about-era practice lists: high-power microscopes, KaVo OP 3D CBCT, iTero Element 5D Plus, digital X-rays at about one-sixth of film dose, an intraoral camera, and electric hand-pieces. Those instruments are why specialty work stays on the Kenner floor.",
  "Hours from the contact page: Monday through Thursday 8:30am–4:00pm, Friday 8:00am–3:00pm. Phone (504) 833-3200. Fax (504) 833-0813. Booking is NexHealth. No email address is printed on the official site, so this rebuild does not invent one.",
  "Insurance listed: Delta Dental, Guardian, Humana, MetLife, Ameritas, Cigna Dental, Renaissance Dental, Aetna, Careington, Dental Plans. Payments: cash, checks, Visa, Mastercard, American Express, Discover, CareCredit, Cherry, Kleer membership. Ask the Kenner desk which of those actually apply to your plan.",
  "The lake office is still 2400 Veterans Blvd. Suite 210, Kenner, LA 70062. Over 30 years of comprehensive dentistry, one Kenner floor, six specialists named on the homepage, and a staff photograph that this rebuild refuses to fake.",
];

export const HOME_LONG = [
  "Lakeside Dental Care is the Kenner dentist at 2400 Veterans Blvd. Suite 210: one glass plaza, one fountain court, one floor that holds general dentistry, endodontics, periodontics, and orthodontics. The homepage six are Dr. Rubia Kapusta, Dr. Regine Dyer, Dr. Catherine Schwab, Dr. Matthew Henson, Dr. Olivia Stassen, and Dr. Corinthia Wilkerson. Dr. Mahrufa Islam appears on the official staff photograph and is not one of those six names.",
  "The official group still is cropped here at native size. Front row: Schwab, Islam, Kapusta. Back row: Dyer, Henson, Stassen. Blue polos are staff. A second still names Anne, Dr. Dyer, Rosie, and Carol. Atmospheric plates of the lake, an empty operatory, a corridor, porcelain, and dusk are not people and are not labeled as the team.",
  "Over 30 years is the tenure the practice publishes. The mission sentence on the about page is to promote oral health by becoming the area’s leading provider of comprehensive dentistry while providing the absolute best care and service to patients, plus a commitment to the reconstruction and renewal of New Orleans. The chairs did not move to the Quarter. They stayed in Kenner.",
  "Hours on the contact page: Monday through Thursday 8:30am–4:00pm, Friday 8:00am–3:00pm. Phone (504) 833-3200. Fax (504) 833-0813. Online booking is NexHealth at the official booker. The card on this homepage is a callback, not a reserved chair. No public email is printed, so none is invented here.",
  "Languages at the Kenner desk: English, Spanish, French, Chinese, Vietnamese, Haitian Creole, Portuguese. Staff come from more than seven countries. Interpreters are in the office. Ask for a language when you book so the person who speaks it is actually on the floor that morning.",
  "Insurance listed on the old insurance page: Delta Dental, Guardian, Humana, MetLife, Ameritas, Cigna Dental, Renaissance Dental, Aetna, Careington, Dental Plans. Cash, checks, Visa, Mastercard, American Express, Discover, CareCredit, Cherry, and a Kleer membership for patients without a plan. Confirm in-network. Do not guess from a Metairie or New Orleans employer card.",
  "The instrument list from the advanced-technology page: high-power microscopes, KaVo OP 3D CBCT, iTero Element 5D Plus, digital X-rays at about one-sixth of film, an intraoral camera, electric hand-pieces. A Kenner dentist with that stack can keep a canal, a graft, and an aligner scan in the building.",
  "Sedation is oral conscious sedation and nitrous oxide. The oral-sedation page says a doctor is board certified to administer oral conscious sedation and uses the phrase sleep dentistry for that method. Bring a driver for the pill protocol. Medical history is the gate.",
  "Cities named as served: Kenner, Metairie, New Orleans, LaPlace, Jefferson Parish, Orleans Parish. There is still one suite. Lakeside Shopping Center in Metairie is a mall. Lakeside Dental Care is the Kenner office. Say Suite 210 to the driver.",
  "Parking is the plaza lot. Suite 210 is upstairs. Friday at 3:00pm is a hard close. A 3:40 arrival from Bywater, Fat City, or LaPlace meets a locked door. Call before you leave the house.",
  "This Kenner dentist rebuild does not invent reviews, star ratings, or an owner origin story beyond “over 30 years.” JSON-LD on these pages has no Review and no aggregateRating. Facebook is facebook.com/lakesidedentalcarekenner. That is the published sameAs.",
  "Book the lake office or dial (504) 833-3200. 2400 Veterans Blvd. Suite 210, Kenner, LA 70062. Ask for the doctor by name. A Kenner dentist with six specialists is still one address.",
  "The staircase of care on this homepage is cosmetic, general, endodontics, and orthodontics — four rooms from the published menu. Periodontics, implants, and sedation live on their own pages and in the same Kenner suite. Footer links are the rest of the map.",
  "Official booking remains NexHealth. The Kenner phone remains (504) 833-3200. Fax remains (504) 833-0813. The fountain court remains the landmark. This Kenner dentist site is a rebuild of facts from lakesidedentalcare.com, not a second clinic.",
  "Staff from more than seven countries work this Kenner floor. The published interpreter list is Spanish, French, Chinese, Vietnamese, Haitian Creole, and Portuguese, plus English at the desk. Ask for a language when you book so the person who speaks it is on the floor that morning.",
  "Jefferson Parish and Orleans Parish are named as served markets. Kenner is still the only suite. If a listing shows a Saturday or a second chair, it is not the contact page this rebuild uses. Monday through Thursday 8:30am–4:00pm, Friday 8:00am–3:00pm.",
];

export function pageCopy<T extends string>(base: Record<T, string[]>, extra: Record<T, string[]>, slug: T) {
  const paras = base[slug];
  const more = extra[slug];
  return [...paras.slice(0, -1), ...more, paras[paras.length - 1]];
}

export const SERVICE_MORE: Record<ServiceSlug, string[]> = {
  "cosmetic-dentistry": [
    "A Kenner cosmetic dentist consult is photographs, shade tabs, and a conversation about which teeth actually show when you speak. Zoom will not lift tetracycline or the inside of an old crown. Porcelain will. The plan should say which.",
    "Same-suite ortho matters when a gap is really a tooth in the wrong place. Dr. Schwab can move it; Dr. Henson can then veneer what remains. Doing porcelain first on a crowded arch is how people pay twice.",
    "Lab turnaround is not published as a number of days. Ask. A Kenner veneer try-in that lands on a Friday at 2:00pm still has to finish before 3:00pm. Book the long chair on a Monday through Thursday.",
    "This page’s images of porcelain are empty atmospheres. Official faces are the doctors. No stock smile is labeled as a Lakeside patient. If you want cases, the old site’s gallery captions name Dr. Henson’s work — not a generated mouth.",
    "Whitening a tooth that already has a crown or a veneer will not change the porcelain. The Kenner cosmetic dentist has to say that out loud before Zoom gel goes on. Bleach the natural neighbors, then decide if the restoration still matches.",
    "Night photographs and a phone flash are not a shade map. Bring a printed picture in daylight. Dr. Kapusta and Dr. Henson plan veneers against that still, not against a filter. Suite 210 is on Veterans; the light in the chair is the light that counts.",
    "Insurance may pay a crown that replaces missing walls and decline a veneer that is shade-only. Ask the Kenner desk for the code before the lab starts. CareCredit, Cherry, and Kleer exist when the plan stops at the gumline.",
    "Book this Kenner cosmetic dentist through NexHealth or (504) 833-3200. Name veneers, crowns, or Zoom on the ticket so the chair is not a hygiene slot with a shade tab tacked on.",
  ],
  "general-dentistry": [
    "A Kenner dentist exam includes the periodontal chart the hygienist already started. Pockets that belong to Dr. Wilkerson should be named in the same visit, not three months later after a “watch.” Ask for the numbers.",
    "Composite is the published filling material. If a tooth is too broken for composite, the conversation becomes a crown with the same general dentists, not a mystery referral. Suite 210 is supposed to hold that next step.",
    "Digital X-rays at one-sixth of film dose still require a reason. This Kenner dentist office does not advertise a full-mouth series as a souvenir. Guidelines, not a coupon, decide the sensor.",
    "Continuity is a name on the chart. Dr. Kapusta, Dr. Henson, and Dr. Stassen are three chairs. Tell the desk which general dentist you already saw so a filling margin is not reinvented by a stranger on the same floor.",
    "A cracked cusp you can see on the intraoral camera is easier to consent to than a sentence about “a little work.” This Kenner dentist office puts the camera on the monitor. Ask to see the tooth before you nod.",
    "Child visits and sealants are on the published general list. Dr. Stassen’s bio says all ages. A Kenner family can keep a six-year molar and a parent crown on the same floor, with Dr. Schwab down the hall if the crowding is next.",
    "Same-week hygiene is a phone question, not a form promise. Hours end at 4:00pm most weekdays and 3:00pm Friday. Call (504) 833-3200. The Kenner dentist chair is real; the web callback is not a reserved cleaning.",
    "Bring the listed insurance card or ask about Kleer. General dentistry is the floor the specialists stand on. Keep the recall the hygienist writes down, at 2400 Veterans Blvd. Suite 210.",
  ],
  endodontics: [
    "A Kenner endodontist visit starts with the tooth number. Insurance files molars differently from anteriors, and retreatment differently from a first canal. Bring the card. Guessing at the window wastes the microscope time.",
    "Swelling, a bad taste, or a tooth that hurts to hot then goes silent are the usual reasons the general dentist walks you down the hall. This page does not diagnose from a sentence. It names the doctor who will.",
    "Apicoectomy is surgery at the root tip when a canal cannot be cleaned from the crown. It is on the published endodontic list. Ask Dr. Dyer if your tooth is a retreat, an apico, or an extraction handed to the periodontist.",
    "After the canal, a temporary is not a crown. The Kenner general dentist who restores it should already be on the schedule. Request that pairing when you book Dr. Dyer so the tooth is not left in a temp for a season.",
    "Dr. Dyer teaches part-time in LSU’s Department of Endodontics. That is an official title, not a brochure adjective. A Kenner endodontist who still teaches is why a difficult molar can stay in Suite 210 instead of a hospital OR.",
    "GentleWave is on the practice Facebook page as fluid dynamics plus sound. Files still go in the canal. This rebuild does not invent a success rate. Ask Dr. Dyer which anatomy she uses it on and which she does not.",
    "Pain that wakes you at 2am is still a weekday chair. Friday close is 3:00pm. Call (504) 833-3200 in the morning, not at lunch, if you want the Kenner endodontist the same day the tooth declared itself.",
    "Bring outside films on a disc if another office started the canal. Do not assume a Metairie periapical is in the Kenner chart. Dr. Dyer should see the anatomy before the rubber dam goes on.",
  ],
  periodontics: [
    "A Kenner periodontist evaluation is pocket depths, bleeding points, and a look at bone on the radiograph or the KaVo OP 3D. “Deep cleaning” is not a vibe. It is a code. Ask which one you are being scheduled for.",
    "Connective-tissue grafts cover roots and thicken thin gum before braces or veneers. The smile gallery already shows Dr. Wilkerson doing that work next to Dr. Henson’s porcelain. That pairing is the Kenner product.",
    "Implant maintenance is periodontal work. A fixture that weeps at a hygiene visit is not a polishing problem. It is Dr. Wilkerson’s problem. Say peri-implant when you call (504) 833-3200 so the slot is not a regular cleaning.",
    "This rebuild will not generate Dr. Wilkerson’s face. The official group photograph does not include her. The periodontist page bio is the source. Initials on a navy field are the honest portrait.",
    "Osseous surgery reshapes bone around teeth the hygienist cannot maintain with a scaler. Crown lengthening exposes a margin so a Kenner crown has somewhere to sit. Both are on the published periodontal menu. Ask which one the pocket chart actually points to.",
    "Guided bone and tissue regeneration are in Dr. Wilkerson’s Harvard-era skill list. A thin ridge that needs an implant later starts here, on the KaVo OP 3D, not on a guess from a 2D bitewing. The restoration still returns to the general dentists in the same suite.",
    "Maintenance after active therapy is its own recall. You do not graduate because the pockets closed once. The Kenner periodontist and the general dentist split that calendar. Write both names down.",
    "Book a periodontal evaluation, not a generic cleaning, if you already know the numbers are the problem. (504) 833-3200 or NexHealth. Suite 210. Metairie, New Orleans, and LaPlace patients keep the rest of the mouth here too.",
    "Gum disease is named on the old maintenance page as the leading cause of adult tooth loss. The Kenner periodontist is how this office tries not to donate those teeth to a partial. Hygiene recall after surgery is the rest of the sentence, not an optional extra.",
  ],
  orthodontics: [
    "A Kenner orthodontist consult is a scan, a conversation about aligners versus braces, and an honest split between Dr. Schwab’s comprehensive mechanics and Dr. Stassen’s limited Invisalign. Those are not interchangeable chairs.",
    "Thin gum plus braces is a perio problem first. Dr. Wilkerson can graft; Dr. Schwab can then move teeth through tissue that will survive. Skipping the graft is how roots show after the retainers.",
    "Adults who work Veterans Blvd offices can do aligner checks without a teen waiting room. Children still come. The site does not age-gate Dr. Schwab. The desk will tell you what after-school inventory actually exists.",
    "Retainers are the unglamorous half. This Kenner orthodontist page does not name a retailer. Ask what she issues, how long you wear it, and what a lost tray costs before the last aligner is printed.",
    "iTero Element 5D Plus is the digital impression system on the technology page. Putty trays are not the starting ritual for Dr. Schwab’s aligner cases. The scan lives in Kenner. You do not drive to a mall kiosk for the STL.",
    "Corrective jaw surgery is mentioned on the old orthodontic summary. Suite 210 is not an operating room. Ask which skeletal cases she keeps and which she coordinates with a surgeon. Get that split in writing.",
    "Insurance ortho riders are not cleaning benefits. Delta on a Metairie card may still have a lifetime ortho maximum of zero. CareCredit and Cherry exist for the months of trays. Ask the Kenner desk for a breakdown before the first aligner.",
    "Book Dr. Schwab at 2400 Veterans Blvd. Suite 210. NexHealth or (504) 833-3200. Bring any prior panorex. Leave with aligners, braces, or a referral — named, not implied.",
    "A Kenner orthodontist who taught at LSU until 2015 still plans cases with Roth-Williams occlusion in the background. That is why a bite complaint is not handed a stack of aligners without a look at how the teeth meet. Ask her what she is actually moving.",
  ],
  "dental-implants": [
    "A Kenner implant consult without a CBCT is a guess. The KaVo OP 3D is in Suite 210 for sinus floors and nerve canals. Ask for the scan on the same day as the exam so a LaPlace or New Orleans drive is not doubled.",
    "Four upper implants under a denture is a published Henson case, not a template for your jaw. Bone volume decides. Dr. Wilkerson’s regeneration list is how a thin ridge becomes a maybe.",
    "Bridges and dentures remain on the homepage replacement set. An honest Kenner implant visit names those when you are not a candidate. Surgery is not the only sentence in the room.",
    "Healing months are not a marketing cycle. Grafts add time. Immediate provisionals happen only when the case was designed that way. Get the sequence in writing: scan, graft if needed, fixture, restore.",
    "Hygiene after the crown is periodontal. Peri-implant disease is in Dr. Wilkerson’s bio because fixtures fail quietly. Stay on recall in Kenner, not on a “call us if it hurts” postcard.",
    "Medications that thin bone or dry the mouth belong on the implant intake. Bring the list. A Kenner implant chair that skips the medical history is how fixtures get placed in a ridge that will not hold them.",
    "Sinus floors on the upper posterior are why the KaVo OP 3D exists. A 2D panorex can hide the air space. Ask for the 3D before anyone promises a fixture in a molar site. That scan is in Suite 210.",
    "Single-tooth implants, short-span bridges on fixtures, and implant-retained dentures are different plans. The homepage lists implants next to dentures and bridges. The consult should pick one, not all three in a blur.",
    "Call (504) 833-3200 or book NexHealth for the 3D visit. 2400 Veterans Blvd. Suite 210. Kenner implant dentistry starts with bone on a screen, not with a catalog tooth on a tray.",
    "Insurance often treats implants as major or excluded. The listed carriers, CareCredit, Cherry, and Kleer are the published payment stack. Get the code and the estimate before the surgical date so a Kenner implant plan is a number, not a surprise at the window.",
    "Same-arch denture conversions and single-tooth fixtures are different mornings. Ask the Kenner implant consult which one the KaVo volume actually supports before anyone orders a catalog tooth.",
  ],
  "sedation-dentistry": [
    "A Kenner sedation dentist visit is a medical-history gate before it is a pill. Sleep apnea, pregnancy, opioids, alcohol, and the time of the Friday close all change the answer. The board-certified sentence is not a waiver.",
    "Valium, Halcion, Xanax, and Ativan are named as the class on the oral-sedation page. That is not a menu you pick from the waiting-room chair. The doctor chooses, or the visit does not happen.",
    "Nitrous is the shorter protocol. Oral sedation is the driver protocol. Do not mix them in your head. Ask the Kenner desk which one is on the appointment ticket before you arrange a ride from Metairie or LaPlace.",
    "Stacking a canal, a graft, and a crown under one calmer morning is the in-house use of sedation. It still requires local anesthetic and a consent you sign awake. Sleep dentistry here is oral conscious sedation, not an OR.",
    "The old homepage’s 40 percent anxiety and 10 percent phobia figures are their published reason for keeping sedation in the suite. They are not your diagnosis. A Kenner sedation dentist still needs a medical history that matches the pill.",
    "A driver who can wait in the plaza lot is part of oral sedation. A rideshare at the curb is not a plan you should invent. Ask the desk how long you stay after the last procedure before anyone hands you a script.",
    "Nitrous does not require the same escort in every protocol. Do not assume it. The Kenner desk will say which visit needs a second adult. Friday at 2:30pm is too late for a sedated morning that has not started.",
    "Call (504) 833-3200 and ask for a sedation consult. Suite 210, 2400 Veterans Blvd., Kenner. Bring the driver and the medication list. Leave with a written list of what you may not do after the appointment.",
    "Oral conscious sedation is the method the practice also calls sleep dentistry. You are not in an OR. You still hear, still sign, still get numb. The Kenner sedation dentist is the layer above the needle for people who would otherwise cancel the whole plan.",
  ],
};

export const AREA_MORE: Record<AreaSlug, string[]> = {
  kenner: [
    "A Kenner dentist appointment is a plaza-lot, elevator, Suite 210 sequence. The fountain court is the landmark the official exterior shows. Do not look for a strip-mall tooth sign on Williams; the glass building on Veterans is the one.",
    "Airport hotels are not a shuttle stop. If you land at Armstrong and want a Kenner dentist the same week, you still live on the contact-page clock. Call (504) 833-3200. NexHealth if you already know the doctor.",
    "Power Boulevard, Vintage Drive, and the lake-side neighborhoods off Williams all funnel to Veterans. 70062 is the zip on the door. Jefferson Parish is the served market; Kenner is the only chair.",
    "Ask for the doctor by last name: Kapusta, Dyer, Schwab, Henson, Stassen, Wilkerson. A generic “dentist” slot at this Kenner office wastes the specialist stack. The desk cannot guess which chair you meant.",
    "Laketown Harbor, the Pontchartrain Center, and the airport road are the Kenner landmarks that sit near Veterans. Suite 210 is none of those; it is the second floor of the glass plaza with the fountain court. The official exterior photograph is the building.",
    "Kenner City Park and the Williams Blvd corridor feed the same office. You do not need a New Orleans specialist for a canal if Dr. Dyer is already on this floor. That is the Kenner dentist pitch the homepage makes.",
    "Friday 3:00pm is a hard stop. A 2:50pm checkout from a Kenner warehouse job will miss a 3:00 close. Monday through Thursday to 4:00pm is the wider window. Call (504) 833-3200 before you leave the lot you are already in.",
    "This Kenner dentist page does not invent a second chair in Metairie. 2400 Veterans Blvd. Suite 210, Kenner, LA 70062. NexHealth or the phone. Ask for the doctor by name.",
    "Esplanade Mall traffic and the airport hotels sit on the same Veterans spine. They are not a reason to skip the hour check. This Kenner dentist office runs the contact-page clock, not a tourist clinic. Call before you leave the hotel lot.",
  ],
  metairie: [
    "Metairie to Kenner on Veterans is a corridor, not a pilgrimage. Clearview to the fountain plaza is the boring route. Fat City and Old Metairie still end at Suite 210. There is no Metairie Lakeside Dental Care clinic hiding behind the mall name.",
    "Dr. Stassen’s Metairie address is her home, per the bio. Your chart still files from Kenner. Bring the Metairie employer card and let the desk tell you if Delta, Guardian, or MetLife actually pays from 70062.",
    "After-school ortho for Metairie kids competes with every Jefferson Parish office. Call. The NexHealth leftover at 7pm does not exist. Monday through Thursday to 4:00pm, Friday to 3:00pm.",
    "If the complaint is crowding plus a dark tooth, book the Kenner exam as a consult, not a cleaning. Dr. Schwab and Dr. Henson can share that morning. A closer Metairie cleaner cannot.",
    "Lakeside Shopping Center is a Metairie mall. Lakeside Dental Care is a Kenner office. Tell the rideshare “2400 Veterans Blvd Suite 210, Kenner” or you will be dropped at the mall fountain. The dental fountain court is a different plaza.",
    "Bonnabel, Causeway, and the 17th Street Canal side all still dump onto Veterans heading west. That is the Metairie-to-Kenner commute this office is built for. There is no shuttle. There is a plaza lot.",
    "Spanish and Vietnamese sit on the published language list, which matters on this corridor. Ask when you book. A Metairie household that waits until the window is how an interpreter’s morning gets missed.",
    "Drive from Metairie to the Kenner dentist. Park at the plaza. Elevator to 210. Book NexHealth if you know the doctor. Call (504) 833-3200 if you do not. Hours: Mon–Thu 8:30–4, Friday 8–3.",
    "Old Metairie oak streets and Fat City night lots both end at the same Kenner suite. The specialist stack — endo, perio, ortho, general — is the reason to leave a closer cleaner. One intake. One chart. One plaza fountain.",
    "A Metairie dentist search that stops at the mall name is how people miss Suite 210. Lakeside Dental Care is the Kenner chair on Veterans, not a kiosk at Lakeside Shopping Center. Put Kenner in the GPS.",
  ],
  "new-orleans": [
    "New Orleans to the Kenner dentist is I-10 west plus Veterans, not a streetcar. CBD parking is what you are skipping. The plaza lot is what you get. The French Quarter does not have a Lakeside operatory.",
    "Orleans Parish is listed as served because metropolitan patients keep this Kenner floor busy, not because a second office opened Uptown. Dr. Dyer’s New Orleans birthplace and Dr. Henson’s city paragraph do not move the chairs.",
    "Haitian Creole, Spanish, Vietnamese, French, Chinese, and Portuguese are published. A New Orleans household that needs one of those should say so on the booking, not at the window after the interpreter’s shift changed.",
    "Mardi Gras and Jazz Fest do not extend dental hours. Friday still dies at 3:00pm. A Bywater departure at 2:50pm is how New Orleans patients meet a locked Kenner door.",
    "Uptown cleanings are not the product. The product is an LSU-teaching endodontist, a Harvard periodontist, an ABO orthodontist, and three general dentists on one Kenner floor. That is the parish-crossing reason.",
    "The about-page mission names the reconstruction and renewal of New Orleans. The chairs did not move to Canal Street. New Orleans patients still check in at 2400 Veterans Blvd. Suite 210. That split is geography, not a slight.",
    "I-10 west in rain plus a 3:40 arrival is a locked Kenner door. Leave the Bywater, Mid-City, or Uptown house with lake traffic in the estimate. Friday dies at 3:00pm. Monday through Thursday to 4:00pm is the safer window.",
    "Oral sedation for a New Orleans patient who has delayed dentistry still needs a driver who can return to Kenner. A streetcar is not an escort. Ask the desk for the protocol before you book the pill visit.",
    "New Orleans to this Kenner dentist is one appointment, not a tour of specialists. (504) 833-3200. NexHealth for a named doctor. Orleans Parish is served; the operatory is Jefferson.",
    "A New Orleans patient who already has a Uptown hygienist can still keep the specialist work here. Bring the X-rays. The Kenner chart does not magically contain a Magazine Street cleaning. Dr. Dyer and Dr. Wilkerson start from what you actually carry in.",
    "Orleans Parish to this Kenner dentist is still one plaza lot. Skip the CBD garage. Keep the specialist stack. Call (504) 833-3200 before lake traffic eats the Friday 3:00pm close.",
  ],
  laplace: [
    "LaPlace to Kenner is I-10 on a dry morning and a longer story in rain. The Kenner dentist does not run a St. John Parish van. Suite 210 is the chair. Budget the interstate, not the map’s best case.",
    "Stack a parent crown and a teenager aligner check on the same Kenner morning. That is how a river-parish household stops driving the interstate twice in a week. Tell the desk both names when you book.",
    "Spanish at the Kenner desk is published. St. John Parish households that need it should write it in the NexHealth note. An 8:30am slot without that note is how people mime a medical history.",
    "A LaPlace implant consult should include the KaVo OP 3D the same day. Adding a Metairie imaging stop is the old pattern this office exists to kill. Ask for the scan on the ticket.",
    "Saturday is not on the official contact page. Third-party listings that whisper Saturday by appointment are ignored here. Monday through Thursday 8:30–4, Friday 8–3, (504) 833-3200.",
    "Airline Highway is the slow alternative to I-10. If you choose it from LaPlace, you still have to arrive before the Kenner close. The desk will not hold a specialist because the river-parish light cycle ran long.",
    "St. John Parish dentistry that splits a root canal and a crown across two towns is the pattern this office exists to stop. Dr. Dyer and the restoring general dentist share Suite 210. Make the LaPlace drive once per visit type.",
    "A teenager in braces plus a parent who needs a periodontal consult can share a Kenner morning. Name both people when you call. The interstate does not get cheaper because you forgot the second chart.",
    "LaPlace to the Kenner dentist remains 2400 Veterans Blvd. Suite 210. Book NexHealth for a named doctor. Ask the desk to same-day the specialist if the exam finds one. No LaPlace satellite exists.",
    "River-parish households that speak Spanish should say so on the first call. Interpreters are in the Kenner office, per the about page, not on a phone tree. A silent 8:30am arrival is how a medical history gets guessed.",
    "LaPlace families who already split a crown and a canal across two towns can stop. This Kenner dentist office keeps both on Suite 210. Name both procedures when you book so the interstate run is once.",
  ],
};

